language: java

jdk:
  - oraclejdk8
#  - openjdk11

# before_install:
#   - unset TRAVIS
#   - unset _JAVA_OPTIONS
#   - wget http://www.deflaker.org/maven/apache-maven-3.5.0.zip
#   - unzip -qq apache-maven-3.5.0.zip
#   - export M2_HOME=$PWD/apache-maven-3.5.0
#   - export PATH=$M2_HOME/bin:$PATH


addons:
  apt:
    packages:
      - oracle-java8-installer # Updates JDK 8 to the latest available.

script: mvn verify javadoc:jar source:jar -B

after_success:
  - .buildscript/deploy_snapshot.sh

env:
    global:
    - secure: "S0BTJVrF4fUCwhTdmoQY6LYr5r1wgXZ/p8lc5bIgUUsc1Ckalwt7s/GDwPuLJ4702sI5t56Eye2iEIMUjeFJKqebZRsX1C5oYsYFxGi3BGlepstYpmj0gLXuSWqCLniS9zmHXCxLhLkC6KxPVjhDlbq76XQx0o3K1J8oEIj/PCE="
    - secure: "awV7yLXURjlPbTOladsNDZk74KYCNXoiZpAP0gQFfK4Sc0fc7+kg8z/yhdWXeTxjsIZ6m0dVDHTqnH8ytnydwXpBam8JdQJ+EAWA6R3Svq1BR1bzl/PcZUoz+Xn8lMXdU3yA1p4qtQlUhMxwsE3MOVe24HSDJPAu4XeWFj1j3qo="
    - FIREBASE_KEY=AIzaSyDU7I6pnN322BvRNN24jRX52owAvuHH1K4
    
branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

